version: "3.8"
services:

    # PHP
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: docker
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - app-network

    # Nginx
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - app-network

    # Redis
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
